# Generated by Django 5.0.4 on 2024-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_comment_options_comment_published_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_in',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
